spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/rrss
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp.gmail.com
    port: 587
    username: <gmail-adress>
    password: <password>

application:
  security:
    jwt:
      secret-key: D8AA359A5430D9A922770B8832AF8524744AC26B8A58130605F5968894F2E734
      expiration: 604800000 # 1 min   60000
      refresh-token:
        expiration: 604800000 # 7


constants:
  otp-token-duration: 2


server:
  port: 8081

  #logging:
    #level:
    #org:
    # springframework:
  #   security: DEBUG
